quarkus:
  application:
    name: imdb-search
  otel:
    metrics:
      enabled: true
    logs:
      enabled: true
  log:
    console:
      format: '%d{HH:mm:ss} %-5p [%X{traceId}:%X{spanId}] [%c{2.}] (%t) %s%e%n'
  container-image:
    builder: jib
    group: hrytsenko
    name: ${quarkus.application.name}
    tag: latest
